name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-test-linux:
    strategy:
      matrix:
        toolset: [gcc, clang]
    name: Build-Test Linux ${{ matrix.toolset }}
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Enable i386 architecture
        if: ${{ matrix.build_arch == 'x86' }}
        run: dpkg --add-architecture i386

      - name: Install base packages
        run: |
          apt-get update
          apt-get install -y wget tar git make curl

      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          submodules: recursive

      - name: Configure gcc
        uses: ./.github/actions/configure-gcc
        with:
          gcc_version: 14
          enable_x86: true

      - name: Configure clang
        if: ${{ matrix.toolset == 'clang' }}
        uses: ./.github/actions/configure-clang
        with:
          clang_version: 20
          enable_x86: true

      - name: Premake generate
        working-directory: ${{ github.workspace }}
        env:
          PREMAKE_NO_PROMPT: 1
        run: ./generate.sh --cc=${{ matrix.toolset }}

      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig:$PKG_CONFIG_PATH
          echo "Package config path: $PKG_CONFIG_PATH"
          scripts/build.sh release
          chmod +x build/bin/Release_x86/{AssetConverter,JamFileTool,lrcompile}

      - name: Test
        working-directory: ${{ github.workspace }}/build/lib/Release_x86/tests
        run: |
          ./AssetLibTests

  build-test-windows:
    name: Build-Test Windows
    runs-on: windows-2025-vs2026
    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3.0.0

      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          submodules: recursive

      - name: Premake generate
        working-directory: ${{ github.workspace }}
        env:
          PREMAKE_NO_PROMPT: 1
        run: ./generate.bat

      - name: Build
        working-directory: ${{ github.workspace }}
        run: |
          msbuild /m /p:Configuration=Release /p:Platform=Win32 build
        
      - name: Test
        working-directory: ${{ github.workspace }}/build/lib/Release_x86/tests
        run: |
          $combinedExitCode = 0
          ./AssetLibTests
          $combinedExitCode = [System.Math]::max($combinedExitCode, $LASTEXITCODE)
          exit $combinedExitCode
